// AI Tool Reviews - dynamically generated by Apollo
const tools = [
    {
        id: 'gpt-developer',
        name: 'GPT Developer Assistant',
        description: 'AI pair programmer that provides real-time suggestions while you code',
        rating: 4.8,
        affiliateUrl: 'https://example.com/affiliate/gpt-dev',
        content: 'GPT Developer reduces coding time by 40% according to benchmarks...'
    },
    {
        id: 'ai-docs',
        name: 'AI Documentation Generator',
        description: 'Automatically generates documentation from source code',
        rating: 4.6,
        affiliateUrl: 'https://example.com/affiliate/ai-docs',
        content: 'Supports 15+ languages and saves developers 8 hours/week on average...'
    }
    // Additional tools will be generated programmatically
];

// Generate additional tools
const toolCategories = ['Testing', 'Debugging', 'Refactoring', 'Security', 'Deployment', 'Cloud', 'Data', 'ML'];

for (let i = 3; i <= 50; i++) {
    const category = toolCategories[Math.floor(Math.random() * toolCategories.length)];
    tools.push({
        id: `tool-${i}`,
        name: `${category} AI Assistant #${i}`,
        description: `AI-powered ${category.toLowerCase()} automation toolkit for developers`,
        rating: parseFloat((4 + Math.random() * 0.8).toFixed(1)),
        affiliateUrl: `https://example.com/affiliate/tool-${i}`,
        content: `The ${category} AI Assistant streamlines workflows through...`
    });
}

// Function to generate tool cards
function generateToolCards() {
    const container = document.getElementById('tools-container');
    tools.forEach(tool => {
        const toolElement = document.createElement('div');
        toolElement.className = 'tool';
        toolElement.innerHTML = `
            <h2>${tool.name}</h2>
            <p><strong>Rating:</strong> ${tool.rating}/5</p>
            <p>${tool.description}</p>
            <p>${tool.content}</p>
            <a href="${tool.affiliateUrl}" class="affiliate-link">
                Try ${tool.name} →
            </a>
        `;
        container.appendChild(toolElement);
    });
}

// Generate reviews when page loads
window.onload = generateToolCards;